export const actions = {
  quiz: {
    QUIZ_DATA_FETCHING: "QUIZ_DATA_FETCHING",
    QUIZ_DATA_FETCHED: "QUIZ_DATA_FETCHED",
    QUIZ_DATA_ERROR: "QUIZ_DATA_ERROR",
  },
  quizId: {
    QUIZ_DATA_FETCHING_BY_ID: "QUIZ_DATA_FETCHING_BY_ID",
    QUIZ_DATA_FETCHED_BY_ID: "QUIZ_DATA_FETCHED_BY_ID",
    QUIZ_DATA_ERROR_BY_ID: "QUIZ_DATA_ERROR_BY_ID",
  },
};
